import { Testimonial } from "../types";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    location: 'Residential Customer',
    rating: 5,
    text: 'Amazing work! Our sunken driveway was completely transformed in just one day. The team was professional, clean, and the results exceeded our expectations. Highly recommend!',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Driveway Leveling',
  },
  {
    id: 2,
    name: 'Mike Rodriguez',
    location: 'Commercial Property Owner',
    rating: 5,
    text: 'We had multiple settlement issues in our warehouse floor. The mudjacking team was efficient and professional. The floor is now perfectly level and safe for our operations.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Industrial Floor Leveling',
  },
  {
    id: 3,
    name: 'Jennifer Davis',
    location: 'Homeowner',
    rating: 5,
    text: 'Our patio was a safety hazard with uneven surfaces. The mudjacking process was quick, clean, and the results are beautiful. Our family can now enjoy our outdoor space safely.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Patio Leveling',
  },
  {
    id: 4,
    name: 'Robert Chen',
    location: 'Property Manager',
    rating: 5,
    text: 'Professional service from start to finish. The team handled our commercial parking lot leveling project efficiently. Great communication and excellent results.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Parking Lot Leveling',
  },
  {
    id: 5,
    name: 'Lisa Thompson',
    location: 'Homeowner',
    rating: 5,
    text: 'Our garage floor was sinking and causing water to pool. The mudjacking team fixed it perfectly and even improved the drainage. Couldn\'t be happier with the results!',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Garage Floor Leveling',
  },
  {
    id: 6,
    name: 'David Wilson',
    location: 'Restaurant Owner',
    rating: 5,
    text: 'The foundation of our restaurant was settling and causing structural issues. The mudjacking team stabilized everything perfectly. Our business is back to normal operations.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Foundation Stabilization',
  },
  {
    id: 7,
    name: 'Maria Garcia',
    location: 'Residential Customer',
    rating: 5,
    text: 'Our sidewalk was a trip hazard for our elderly neighbors. The mudjacking team leveled it perfectly and made it safe for everyone. Very professional and caring service.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Sidewalk Leveling',
  },
  {
    id: 8,
    name: 'James Anderson',
    location: 'Commercial Developer',
    rating: 5,
    text: 'We had a large commercial project with multiple settlement issues. The team handled everything efficiently and completed the work ahead of schedule. Excellent quality and service.',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Commercial Foundation Repair',
  },
  {
    id: 9,
    name: 'Amanda Foster',
    location: 'Homeowner',
    rating: 5,
    text: 'Our pool deck was uneven and dangerous. The mudjacking process was fascinating to watch and the results are amazing. Our kids can now play safely around the pool.',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Pool Deck Leveling',
  },
  {
    id: 10,
    name: 'Thomas Martinez',
    location: 'Property Manager',
    rating: 5,
    text: 'Managing multiple properties, I\'ve worked with many contractors. This mudjacking team stands out for their professionalism, quality work, and attention to detail.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Multi-Property Repair',
  },
  {
    id: 11,
    name: 'Rachel Green',
    location: 'Homeowner',
    rating: 5,
    text: 'Our basement floor was uneven and causing moisture issues. The mudjacking team not only leveled the floor but also improved the drainage. Our basement is now dry and usable.',
    avatar: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Basement Floor Leveling',
  },
  {
    id: 12,
    name: 'Kevin O\'Brien',
    location: 'Commercial Property Owner',
    rating: 5,
    text: 'The team handled our large warehouse floor leveling project with precision and efficiency. The floor is now perfectly level and safe for our heavy equipment operations.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150',
    service: 'Warehouse Floor Leveling',
  },
]; 